---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 
  selector:
    matchLabels:
      name: grafana-data-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-data-pv
  namespace: monitoring
  labels:
    name: grafana-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /share-data/grafana
    server: 192.168.3.232