apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data-pv
  namespace: monitoring
  labels:
    app: prometheus-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.3.232
    path: /share-data/prometheus

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager-data-pv
  namespace: monitoring
  labels:
    app: prometheus-alertmanager-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.3.232
    path: /share-data/alertmanager